// push 配信の多クライアント化: `paths:` 付きエントリ → nested AGENTS.md の marker ブロック注入。
//
// rules.mjs が生成する .claude/rules/ は Claude Code 専用のトリガ層で、Codex CLI 等の
// 他エージェントには届かない。他エージェントが自動ロードする事実上唯一のチャネルは
// ディレクトリ階層の AGENTS.md なので、対象ディレクトリの AGENTS.md に BEGIN/END marker で
// 囲んだ自動生成セクション (title + summary + 正本 pointer) を注入する。
// marker の外側 (手書き部分) には一切触れない。
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

export const BEGIN_MARKER = "<!-- BEGIN:wheel-rules -->";
export const END_MARKER = "<!-- END:wheel-rules -->";

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * entry がこの target ディレクトリへ配信されるべきか。
 * - glob が `<targetDir>/` 接頭辞 (または targetDir そのもの) → 配信
 * - glob が `**\/` で始まる普遍 glob → 残りにワイルドカードが無ければ
 *   target 直下の実在チェックで判定 (例: `**\/wrangler.jsonc` は wrangler.jsonc を
 *   持つディレクトリにだけ配信)。ワイルドカードが残る場合は過小配信を避けて全 target に配信
 *   (「知らないことは検索しない」に負けるのは過小配信の側)。
 */
export function entryMatchesTarget(entry, targetDir, repoRoot) {
  for (const glob of entry.paths) {
    if (glob === targetDir || glob.startsWith(`${targetDir}/`)) return true;
    if (glob.startsWith("**/")) {
      const rest = glob.slice(3);
      if (/[*?[]/.test(rest)) return true;
      if (existsSync(join(repoRoot, targetDir, rest))) return true;
    }
  }
  return false;
}

/** 1 target 分の注入ブロック (marker 込み・末尾改行なし)。 */
export function renderAgentsBlock(entries, wheelDir) {
  const lines = entries.map(
    (e) => `- **[${e.id}] ${e.title}** — ${e.summary}\n  Full entry (read it): ${wheelDir}/${e.file}`,
  );
  return `${BEGIN_MARKER}
<!-- AUTO-GENERATED by open-wheel from ${wheelDir} — do not edit this block.
     Edit the wheel entries instead, then re-run: open-wheel rules / gen-wheel-rules.mjs -->
## Wheel: このディレクトリに効く教訓 (変更前に読む)

以下は \`paths:\` がこのディレクトリに該当する wheel エントリの自動注入。
従った / 救われた時は commit message か PR 本文で id を引用すること。

${lines.join("\n")}
${END_MARKER}`;
}

/**
 * 期待される注入結果 (targetDir → ブロック文字列 | null)。
 * null = 該当エントリ無し (ブロックを持つべきでない)。active エントリのみ対象。
 */
export function buildExpectedAgentsBlocks(entries, targets, wheelDir, repoRoot) {
  const expected = new Map();
  for (const target of targets) {
    const hits = entries.filter(
      (e) => e.status === "active" && e.paths.length > 0 && entryMatchesTarget(e, target, repoRoot),
    );
    expected.set(target, hits.length > 0 ? renderAgentsBlock(hits, wheelDir) : null);
  }
  return expected;
}

const BLOCK_RE = new RegExp(`${escapeRegExp(BEGIN_MARKER)}[\\s\\S]*?${escapeRegExp(END_MARKER)}`);

/** 既存テキストへブロックを upsert (marker 置換 / 無ければ末尾追記)。block=null は除去。 */
export function upsertAgentsBlock(existingText, block) {
  if (BLOCK_RE.test(existingText)) {
    if (block === null) {
      return existingText.replace(BLOCK_RE, "").replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "");
    }
    return existingText.replace(BLOCK_RE, block);
  }
  if (block === null) return existingText;
  if (existingText.trim() === "") return `${block}\n`;
  return `${existingText.replace(/\n*$/, "\n\n")}${block}\n`;
}

/** --check: 期待ブロックと disk 上の AGENTS.md の差分一覧 (空 = 同期済み)。 */
export function checkAgentsBlocks(expected, repoRoot) {
  const problems = [];
  for (const [target, block] of expected) {
    const file = join(repoRoot, target, "AGENTS.md");
    const rel = `${target}/AGENTS.md`;
    const text = existsSync(file) ? readFileSync(file, "utf-8") : null;
    const current = text?.match(BLOCK_RE)?.[0] ?? null;
    if (block === null) {
      if (current !== null) problems.push(`orphan block: ${rel} (no active entry targets this dir)`);
      continue;
    }
    if (text === null) problems.push(`missing: ${rel}`);
    else if (current === null) problems.push(`missing block: ${rel}`);
    else if (current !== block) problems.push(`stale: ${rel}`);
  }
  return problems;
}

/** 生成: 各 target の AGENTS.md へ upsert (ファイルが無ければブロックのみで新規作成)。 */
export function writeAgentsBlocks(expected, repoRoot) {
  for (const [target, block] of expected) {
    const file = join(repoRoot, target, "AGENTS.md");
    const exists = existsSync(file);
    if (!exists && block === null) continue;
    const text = exists ? readFileSync(file, "utf-8") : "";
    const next = upsertAgentsBlock(text, block);
    if (next === text && exists) continue;
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, next, "utf-8");
  }
}
